Revert "Upgrade arm-ffa to 0.5.0"
This reverts commit a025365566677b52964f94fa9aac217e4754482d.

Without this, regenerating any crate results in an error:

./crate_tool regenerate anyhow
Regenerating anyhow

thread 'main' (2325827) panicked at crate_tool/src/pseudo_crate.rs:96:18:
called `Result::unwrap()` on an `Err` value: CommandFailedwithOutput { code: Some(101), stdout: "", stderr: "error: failed to select a version for `thiserror`.\n    ... required by package `arm-ffa v0.5.0`\n    ... which satisfies dependency `arm-ffa = \"=0.5.0\"` (locked to 0.5.0) of package `android-pseudo-crate v0.1.0 (/usr/local/google/home/jeffv/android/main-crate-updates/external/rust/android-crates-io/pseudo_crate)`\nversions that meet the requirements `^2.0.18` are: 2.0.18\n\nall possible versions conflict with previously selected packages.\n\n  previously selected package `thiserror v2.0.16`\n    ... which satisfies dependency `thiserror = \"=2.0.16\"` (locked to 2.0.16) of package `android-pseudo-crate v0.1.0 (/usr/local/google/home/jeffv/android/main-crate-updates/external/rust/android-crates-io/pseudo_crate)`\n\nfailed to select a version for `thiserror` which could resolve this conflict\n" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Change-Id: I6c28f56bc565d147f139af8fe94e48f5b41ef01d