Revert "Update spdx to 0.12.0"
This reverts commit 46531ef7caf237640e0e7c5ef8dbd4dc9f203395.

Reason for revert: Requires nightly version of Cargo

error: failed to download `spdx v0.10.9`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/usr/local/google/home/chiw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spdx-0.10.9/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.83.0-dev (5ffbef321 2024-10-29)).
  Consider trying a more recent nightly release.


Change-Id: Iae90ea0b2a1aa7770386744be54fd26f8a5c262c