rustc-demangle-capi: disable native_coverage
rustc-demangle-capi (a.k.a rustc_demangle_static) is used by both
libc_malloc_debug_backtrace and libunwindstack. However,
libc_malloc_debug_backtrace is often excluded from "coverage" build
while libunwindstack is not. This can lead the build failure when both
paths are used by generated_rust_staticlib:

error[E0464]: multiple candidates for `rlib` dependency `rustc_demangle_static` found
 --> out/soong/.intermediates/frameworks/native/libs/zygotebundle/libzygote_bundle/android_x86_64_silvermont_shared_cov/generated_rust_staticlib/librustlibs.rs:4:1
  |
4 | extern crate rustc_demangle_static;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: candidate #1: .../librustc_demangle_static/android_x86_64_silvermont_rlib_rlib-core/librustc_demangle_static.rlib
  = note: candidate #2: .../librustc_demangle_static/android_x86_64_silvermont_rlib_rlib-core_cov/librustc_demangle_static.rlib

Let's disable native coverage.

Bug: 537051482
Flag: build.RELEASE_ZYGOTE_AWARE_PAGE_TABLE_SHARING
Test: presubmit (-coverage target)
Change-Id: I4fdbb6243430c69f7959724ca09076e31dc5688d