Update zerovec to 0.11.6
Enabled the 'alloc' feature in cargo_embargo.json to satisfy dependencies from other crates like potential_utf.
The build failed with "error[E0433]: failed to resolve: could not find maps in zerovec" because "the item is gated behind the alloc feature".

Test: mm
Bug: b/498364090
Change-Id: I59aa7cc8176bd1faecead46bfc76f8eacf5468e6